In [53]:
import pandas as pd
import os

In [54]:
file_path = input('Veulliez entrer le nom du fichier: ')
file_path += '.csv'
if os.path.isfile(file_path):
    with open(file_path, 'r') as f:
        df = pd.read_csv(file_path)
else:
    print(f"The file '{file_path}' does not exist.")

In [55]:
df

,Direction,Year,Date,Weekday,Country,Commodity,Transport_Mode,Measure,Value,Cumulative
0,Exports,2015.0,01/01/2015,Thursday,All,All,All,$,104000000.0,104000000.0
1,Exports,2015.0,02/01/2015,Friday,All,All,All,$,96000000.0,200000000.0
2,Exports,2015.0,03/01/2015,Saturday,All,All,All,$,61000000.0,262000000.0
3,Exports,2015.0,04/01/2015,Sunday,All,All,All,$,74000000.0,336000000.0
4,Exports,2015.0,05/01/2015,Monday,All,All,All,$,105000000.0,442000000.0
...,...,...,...,...,...,...,...,...,...,...
97549,Reimports,2021.0,11/12/2021,Saturday,All,All,All,$,0.0,165000000.0
97550,Reimports,2021.0,12/12/2021,Sunday,All,All,All,$,0.0,165000000.0
97551,Reimports,2021.0,13/12/2021,Monday,All,All,All,$,2000000.0,166000000.0
97552,Reimports,2021.0,14/12/2021,Tuesday,All,All,All,$,1000000.0,167000000.0
97553,Reimports,2021.0,15/12/2021,Wednesday,All,All,All,$,1000000.0,168000000.0

In [56]:
df_clean = df.dropna()
df_clean = df_clean.sample(frac=1).reset_index(drop=True)
df_clean

,Direction,Year,Date,Weekday,Country,Commodity,Transport_Mode,Measure,Value,Cumulative
0,Imports,2019.0,03/01/2019,Thursday,China,Electrical machinery and equip,All,$,14000000.0,1.700000e+07
1,Reimports,2017.0,10/07/2017,Monday,All,All,All,$,0.0,8.400000e+07
2,Exports,2015.0,25/05/2015,Monday,East Asia (excluding China),All,All,$,35000000.0,4.791000e+09
3,Exports,2021.0,18/09/2021,Saturday,Japan,All,All,$,4000000.0,2.569000e+09
4,Imports,2021.0,03/06/2021,Thursday,Australia,All,All,$,49000000.0,2.967000e+09
...,...,...,...,...,...,...,...,...,...,...
68021,Imports,2015.0,21/01/2015,Wednesday,United Kingdom,All,All,$,5000000.0,7.900000e+07
68022,Exports,2019.0,20/06/2019,Thursday,China,Meat and edible offal,All,Tonnes,1000.0,2.390000e+05
68023,Exports,2020.0,03/01/2020,Friday,United States,All,All,$,34000000.0,7.300000e+07
68024,Imports,2020.0,28/04/2020,Tuesday,China,Electrical machinery and equip,All,$,13000000.0,6.180000e+08
68025,Imports,2016.0,29/12/2016,Thursday,United Kingdom,All,All,$,5000000.0,1.454000e+09

In [62]:
json_perc = 0
db_perc = 0

while True:
    json_perc = int(input('Veuillez saisir le pourcentage du fichier json: '))
    if json_perc < 1 or json_perc > 100:
        print("EntrÃ©e non valide ! Veuillez saisir un pourcentage entre 1 et 100.")
    else:
        break

while True:
    db_perc = int(input('Veuillez saisir le pourcentage de la base de donnees: '))
    if db_perc < 1 or db_perc >= 100-json_perc:
        print(f"EntrÃ©e non valide ! Veuillez saisir un pourcentage entre 1 et {100-json_perc}.")
    else:
        break

njs = len(df_clean) * (json_perc / 100)
ndb = len(df_clean) * (db_perc / 100)
ncs = len(df_clean) * ((json_perc + db_perc) / 100)

df_js = df_clean[:round(njs)]
df_db = df_clean[round(ndb):round(ncs)]
df_csv = df_clean[round(ncs):]

print(f"Le nombre de ligne du fichier json est {len(df_js)} pour le pourcentage {json_perc}% ")
print(f"Le nombre de ligne de la base de donnees est {len(df_db)} pour le pourcentage {db_perc}% ")
print(f"Le nombre de ligne du fichier csv est {len(df_csv)} pour le pourcentage {(100 - (json_perc + db_perc))}% ")

Le nombre de ligne du fichier json est 20408 pour le pourcentage 30%
Le nombre de ligne de la base de donnees est 20408 pour le pourcentage 30%
Le nombre de ligne du fichier csv est 27210 pour le pourcentage 40%

In [63]:
# Prompt the user to enter the name of a JSON file
while True:
    nom_json = input('Veuillez saisir le nom du fichier json: ')
    if not nom_json.isidentifier():
        print('Le nom du fichier json doit Ãªtre un identifiant valide.')
    else:
        break

# Prompt the user to enter the name of a database
while True:
    nom_db = input('Veuillez saisir le nom de la base de donnÃ©es: ')
    if not nom_db.isidentifier():
        print('Le nom de la base de donnÃ©es doit Ãªtre un identifiant valide.')
    else:
        break

# Prompt the user to enter the name of a table in the database
while True:
    nom_table = input('Veuillez saisir le nom de la table de votre base de donnÃ©es: ')
    if not nom_table.isidentifier():
        print('Le nom de la table doit Ãªtre un identifiant valide.')
    else:
        break

print('Les noms de fichier JSON, de base de donnÃ©es et de table sont valides!')

df_js.to_json(f'{nom_json}.json', orient='records')
df_csv.to_csv(f'{nom_json}-split.csv', header=False, index=False)
print('le fichier JSON et le fichier CSV sont bien cree!')

Les noms de fichier JSON, de base de donnÃ©es et de table sont valides!
le fichier JSON et le fichier CSV sont bien cree!

In [64]:
import pyodbc as odbc

# Set up the connection string
driver = 'SQL SERVER'
server = 'PC-HICHAM'
database = 'master'

connection_info = f"""
    DRIVER={{{driver}}};
    SERVER={{{server}}};
    DATABASE={{{database}}};
    Trust_Connection=yes;
"""
# Connect to default database
connection = odbc.connect(connection_info)
cursor = connection.cursor()

In [65]:
# create database and use it
cursor.execute(f'''
    IF EXISTS (SELECT name FROM sys.databases WHERE name = '{nom_db}')
        PRINT 'Database {nom_db} exist'
    ELSE
        CREATE DATABASE {nom_db};
''')
#commit changes
connection.commit()

In [67]:
cursor.execute(f''' USE {nom_db} ''')
#commit changes
connection.commit()

In [68]:
# Function to get the SQL Server data type equivalent for DataFrame types
def get_sql_server_type(ctype):
    sql_server_types = {
        'int64': 'INT',
        'object': 'NVARCHAR(max)',
        'bool': 'BIT',
        'float64': 'FLOAT'
    }
    return sql_server_types.get(ctype, 'NVARCHAR(max)')

# Generate the SQL Server column definitions based on DataFrame types
sql_server_columns = ',\n'.join([f'{column} {get_sql_server_type(str(df_db.dtypes[column]))}' for column in df_db.columns])

# SQL Server CREATE TABLE statement
create_table_sql = f''' CREATE TABLE {nom_table} ( {sql_server_columns});'''

# print(create_table_sql)
cursor.execute(create_table_sql)
connection.commit()

In [69]:
column_names = ', '.join(df_db.columns)

value_placeholders = ', '.join(['?' for _ in df_db.columns])

# Generate the SQL Server INSERT INTO statement
insert_query = f"INSERT INTO {nom_table} ({column_names}) VALUES ({value_placeholders})"
cursor.cancel()
# Execute the INSERT INTO statement for each row of data in the DataFrame
for _, row in df_db.iterrows():
    values = tuple(row.values)
    cursor.execute(insert_query, values)
    print(f'success insertion of row {values} .')

# Commit the changes and close the connection
connection.commit()

success insertion of row ('Exports', 2015.0, '10/11/2015', 'Tuesday', 'European Union (27)', 'All', 'All', '$', 5000000.0, 3127000000.0) .
success insertion of row ('Exports', 2016.0, '06/09/2016', 'Tuesday', 'All', 'All', 'All', '$', 79000000.0, 33450000000.0) .
success insertion of row ('Exports', 2015.0, '16/08/2015', 'Sunday', 'Total (excluding China)', 'All', 'All', '$', 71000000.0, 25937000000.0) .
success insertion of row ('Exports', 2017.0, '27/05/2017', 'Saturday', 'Australia', 'All', 'All', '$', 12000000.0, 3304000000.0) .
success insertion of row ('Exports', 2019.0, '22/04/2019', 'Monday', 'China', 'Meat and edible offal', 'All', '$', 5000000.0, 1084000000.0) .
success insertion of row ('Exports', 2016.0, '23/04/2016', 'Saturday', 'All', 'Non-food manufactured goods', 'All', '$', 36000000.0, 4062000000.0) .
success insertion of row ('Exports', 2020.0, '20/01/2020', 'Monday', 'All', 'All', 'Air', '$', 10000000.0, 286000000.0) .
success insertion of row ('Imports', 2019.0, '26/11/2019', 'Tuesday', 'All', 'Mechanical machinery and equip', 'All', '$', 34000000.0, 8442000000.0) .
success insertion of row ('Exports', 2017.0, '25/10/2017', 'Wednesday', 'All', 'Fruit', 'All', '$', 0.0, 2531000000.0) .
success insertion of row ('Exports', 2021.0, '14/09/2021', 'Tuesday', 'United Kingdom', 'All', 'All', '$', 6000000.0, 992000000.0) .
success insertion of row ('Exports', 2015.0, '30/03/2015', 'Monday', 'All', 'Fruit', 'All', '$', 5000000.0, 202000000.0) .
success insertion of row ('Exports', 2017.0, '17/10/2017', 'Tuesday', 'European Union (27)', 'All', 'All', '$', 6000000.0, 3003000000.0) .
success insertion of row ('Exports', 2015.0, '19/05/2015', 'Tuesday', 'Total (excluding China)', 'All', 'All', '$', 81000000.0, 16010000000.0) .
success insertion of row ('Imports', 2020.0, '25/12/2020', 'Friday', 'China', 'Mechanical machinery and equip', 'All', '$', 0.0, 2342000000.0) .
success insertion of row ('Imports', 2015.0, '24/12/2015', 'Thursday', 'China', 'All', 'All', '$', 28000000.0, 10161000000.0) .
success insertion of row ('Exports', 2017.0, '09/06/2017', 'Friday', 'United States', 'Meat and edible offal', 'All', 'Tonnes', 0.0, 130000.0) .
success insertion of row ('Imports', 2020.0, '17/05/2020', 'Sunday', 'Australia', 'All', 'All', '$', 2000000.0, 2329000000.0) .
success insertion of row ('Exports', 2015.0, '27/11/2015', 'Friday', 'European Union (27)', 'All', 'All', '$', 7000000.0, 3260000000.0) .
success insertion of row ('Exports', 2018.0, '04/12/2018', 'Tuesday', 'All', 'Meat and edible offal', 'All', '$', 21000000.0, 6860000000.0) .
success insertion of row ('Imports', 2015.0, '17/10/2015', 'Saturday', 'All', 'All', 'Sea', '$', 11000000.0, 31787000000.0) .
success insertion of row ('Exports', 2015.0, '31/08/2015', 'Monday', 'All', 'Meat and edible offal', 'All', '$', 19000000.0, 4919000000.0) .
success insertion of row ('Imports', 2021.0, '05/08/2021', 'Thursday', 'China', 'All', 'All', '$', 50000000.0, 8784000000.0) .
success insertion of row ('Exports', 2015.0, '24/06/2015', 'Wednesday', 'All', 'Fruit', 'All', '$', 1000000.0, 1314000000.0) .
success insertion of row ('Exports', 2020.0, '05/10/2020', 'Monday', 'All', 'All', 'Air', '$', 9000000.0, 4587000000.0) .
success insertion of row ('Exports', 2020.0, '19/10/2020', 'Monday', 'All', 'All', 'Air', '$', 10000000.0, 4846000000.0) .
success insertion of row ('Exports', 2017.0, '19/03/2017', 'Sunday', 'All', 'Meat and edible offal', 'All', 'Tonnes', 3000.0, 260000.0) .
success insertion of row ('Exports', 2015.0, '22/06/2015', 'Monday', 'All', 'All', 'Sea', '$', 210000000.0, 21535000000.0) .
success insertion of row ('Exports', 2017.0, '21/07/2017', 'Friday', 'United States', 'Meat and edible offal', 'All', 'Tonnes', 0.0, 164000.0) .
success insertion of row ('Imports', 2021.0, '24/01/2021', 'Sunday', 'United Kingdom', 'All', 'All', '$', 1000000.0, 87000000.0) .
success insertion of row ('Imports', 2020.0, '29/06/2020', 'Monday', 'All', 'Non-food manufactured goods', 'All', '$', 138000000.0, 19803000000.0) .
success insertion of row ('Imports', 2020.0, '11/04/2020', 'Saturday', 'China', 'All', 'All', '$', 3000000.0, 2936000000.0) .
success insertion of row ('Exports', 2017.0, '20/06/2017', 'Tuesday', 'All', 'Fruit', 'All', '$', 6000000.0, 1527000000.0) .
success insertion of row ('Imports', 2016.0, '26/04/2016', 'Tuesday', 'China', 'Electrical machinery and equip', 'All', '$', 7000000.0, 549000000.0) .
success insertion of row ('Exports', 2016.0, '16/03/2016', 'Wednesday', 'All', 'Non-food manufactured goods', 'All', '$', 27000000.0, 2729000000.0) .
success insertion of row ('Imports', 2020.0, '09/11/2020', 'Monday', 'All', 'Non-food manufactured goods', 'All', '$', 180000000.0, 36087000000.0) .
success insertion of row ('Exports', 2017.0, '14/07/2017', 'Friday', 'All', 'All', 'Air', '$', 17000000.0, 2905000000.0) .
success insertion of row ('Exports', 2015.0, '19/01/2015', 'Monday', 'Japan', 'All', 'All', '$', 2000000.0, 71000000.0) .
success insertion of row ('Imports', 2016.0, '13/08/2016', 'Saturday', 'All', 'All', 'Sea', '$', 9000000.0, 23402000000.0) .
success insertion of row ('Imports', 2016.0, '14/12/2016', 'Wednesday', 'All', 'Mechanical machinery and equip', 'All', '$', 38000000.0, 6523000000.0) .
success insertion of row ('Exports', 2021.0, '26/10/2021', 'Tuesday', 'China', 'Meat and edible offal', 'All', 'Tonnes', 1000.0, 392000.0) .
success insertion of row ('Imports', 2015.0, '08/07/2015', 'Wednesday', 'All', 'All', 'Sea', '$', 129000000.0, 19644000000.0) .
success insertion of row ('Imports', 2021.0, '12/02/2021', 'Friday', 'All', 'All', 'All', '$', 197000000.0, 6806000000.0) .
success insertion of row ('Exports', 2021.0, '05/11/2021', 'Friday', 'Japan', 'All', 'All', '$', 6000000.0, 2996000000.0) .
success insertion of row ('Exports', 2016.0, '30/08/2016', 'Tuesday', 'China', 'Meat and edible offal', 'All', 'Tonnes', 0.0, 164000.0) .
success insertion of row ('Imports', 2021.0, '17/06/2021', 'Thursday', 'All', 'All', 'Air', '$', 52000000.0, 5989000000.0) .
success insertion of row ('Exports', 2021.0, '01/07/2021', 'Thursday', 'European Union (27)', 'All', 'All', '$', 8000000.0, 2108000000.0) .
success insertion of row ('Imports', 2021.0, '24/06/2021', 'Thursday', 'China', 'All', 'All', '$', 50000000.0, 6888000000.0) .
success insertion of row ('Exports', 2015.0, '21/03/2015', 'Saturday', 'European Union (27)', 'All', 'All', '$', 17000000.0, 711000000.0) .
success insertion of row ('Exports', 2021.0, '11/07/2021', 'Sunday', 'All', 'All', 'Air', '$', 11000000.0, 3100000000.0) .
success insertion of row ('Exports', 2015.0, '07/05/2015', 'Thursday', 'China', 'Meat and edible offal', 'All', '$', 3000000.0, 494000000.0) .
success insertion of row ('Imports', 2021.0, '16/06/2021', 'Wednesday', 'China', 'All', 'All', '$', 50000000.0, 6524000000.0) .
success insertion of row ('Exports', 2015.0, '18/08/2015', 'Tuesday', 'United Kingdom', 'All', 'All', '$', 5000000.0, 1110000000.0) .
success insertion of row ('Exports', 2020.0, '13/07/2020', 'Monday', 'Australia', 'All', 'All', '$', 26000000.0, 4224000000.0) .
success insertion of row ('Exports', 2020.0, '20/10/2020', 'Tuesday', 'United Kingdom', 'All', 'All', '$', 7000000.0, 1259000000.0) .
success insertion of row ('Exports', 2021.0, '08/05/2021', 'Saturday', 'Total (excluding China)', 'All', 'All', '$', 110000000.0, 14442000000.0) .
success insertion of row ('Exports', 2018.0, '04/02/2018', 'Sunday', 'All', 'All', 'All', '$', 177000000.0, 4928000000.0) .
success insertion of row ('Imports', 2019.0, '07/01/2019', 'Monday', 'All', 'Mechanical machinery and equip', 'All', '$', 37000000.0, 142000000.0) .
success insertion of row ('Imports', 2020.0, '27/06/2020', 'Saturday', 'China', 'All', 'All', '$', 1000000.0, 5636000000.0) .
success insertion of row ('Imports', 2020.0, '16/04/2020', 'Thursday', 'All', 'All', 'All', '$', 178000000.0, 16672000000.0) .
success insertion of row ('Imports', 2021.0, '23/10/2021', 'Saturday', 'All', 'All', 'All', '$', 67000000.0, 55150000000.0) .
success insertion of row ('Exports', 2017.0, '11/11/2017', 'Saturday', 'All', 'All', 'Sea', '$', 73000000.0, 40203000000.0) .
success insertion of row ('Imports', 2016.0, '09/11/2016', 'Wednesday', 'All', 'All', 'Air', '$', 41000000.0, 10355000000.0) .
success insertion of row ('Exports', 2015.0, '27/06/2015', 'Saturday', 'All', 'Non-food manufactured goods', 'All', '$', 22000000.0, 6395000000.0) .
success insertion of row ('Exports', 2016.0, '12/06/2016', 'Sunday', 'All', 'Meat and edible offal', 'All', '$', 36000000.0, 3436000000.0) .
success insertion of row ('Exports', 2015.0, '12/05/2015', 'Tuesday', 'United States', 'Meat and edible offal', 'All', '$', 3000000.0, 896000000.0) .
success insertion of row ('Imports', 2021.0, '31/01/2021', 'Sunday', 'All', 'All', 'Air', '$', 19000000.0, 957000000.0) .
success insertion of row ('Exports', 2020.0, '07/09/2020', 'Monday', 'All', 'Meat and edible offal', 'All', '$', 13000000.0, 5998000000.0) .
success insertion of row ('Exports', 2015.0, '27/05/2015', 'Wednesday', 'All', 'Fruit', 'All', '$', 4000000.0, 968000000.0) .
success insertion of row ('Exports', 2021.0, '10/12/2021', 'Friday', 'All', 'Non-food manufactured goods', 'All', '$', 52000000.0, 12396000000.0) .
success insertion of row ('Exports', 2017.0, '07/05/2017', 'Sunday', 'All', 'Meat and edible offal', 'All', '$', 43000000.0, 2734000000.0) .
success insertion of row ('Imports', 2015.0, '14/04/2015', 'Tuesday', 'Australia', 'All', 'All', '$', 21000000.0, 1591000000.0) .
success insertion of row ('Exports', 2017.0, '13/05/2017', 'Saturday', 'All', 'All', 'All', '$', 163000000.0, 19254000000.0) .
success insertion of row ('Reimports', 2015.0, '20/03/2015', 'Friday', 'All', 'All', 'All', '$', 3000000.0, 46000000.0) .
success insertion of row ('Exports', 2021.0, '08/11/2021', 'Monday', 'European Union (27)', 'All', 'All', '$', 3000000.0, 3511000000.0) .
success insertion of row ('Imports', 2017.0, '17/05/2017', 'Wednesday', 'China', 'Mechanical machinery and equip', 'All', '$', 4000000.0, 654000000.0) .
success insertion of row ('Imports', 2021.0, '10/09/2021', 'Friday', 'United Kingdom', 'All', 'All', '$', 4000000.0, 1118000000.0) .
success insertion of row ('Exports', 2019.0, '01/01/2019', 'Tuesday', 'United States', 'Meat and edible offal', 'All', 'Tonnes', 0.0, 0.0) .
success insertion of row ('Imports', 2016.0, '17/01/2016', 'Sunday', 'Australia', 'All', 'All', '$', 5000000.0, 220000000.0) .
success insertion of row ('Exports', 2021.0, '22/09/2021', 'Wednesday', 'European Union (27)', 'All', 'All', '$', 24000000.0, 3092000000.0) .
success insertion of row ('Exports', 2020.0, '15/12/2020', 'Tuesday', 'China', 'All', 'All', '$', 42000000.0, 15745000000.0) .
success insertion of row ('Imports', 2021.0, '14/06/2021', 'Monday', 'All', 'Non-food manufactured goods', 'All', '$', 212000000.0, 21646000000.0) .
success insertion of row ('Imports', 2015.0, '01/02/2015', 'Sunday', 'China', 'Electrical machinery and equip', 'All', '$', 1000000.0, 119000000.0) .
success insertion of row ('Imports', 2015.0, '29/07/2015', 'Wednesday', 'All', 'Mechanical machinery and equip', 'All', '$', 25000000.0, 3712000000.0) .
success insertion of row ('Imports', 2017.0, '20/07/2017', 'Thursday', 'China', 'Electrical machinery and equip', 'All', '$', 8000000.0, 1055000000.0) .
success insertion of row ('Exports', 2020.0, '04/07/2020', 'Saturday', 'Total (excluding China)', 'All', 'All', '$', 65000000.0, 23617000000.0) .
success insertion of row ('Exports', 2018.0, '26/09/2018', 'Wednesday', 'All', 'All', 'All', '$', 137000000.0, 41760000000.0) .
success insertion of row ('Exports', 2015.0, '29/08/2015', 'Saturday', 'All', 'Meat and edible offal', 'All', '$', 9000000.0, 4889000000.0) .
success insertion of row ('Exports', 2017.0, '31/10/2017', 'Tuesday', 'China', 'Meat and edible offal', 'All', 'Tonnes', 0.0, 199000.0) .
success insertion of row ('Imports', 2016.0, '01/06/2016', 'Wednesday', 'United Kingdom', 'All', 'All', '$', 7000000.0, 584000000.0) .
success insertion of row ('Exports', 2021.0, '19/06/2021', 'Saturday', 'United States', 'Meat and edible offal', 'All', '$', 3000000.0, 960000000.0) .
success insertion of row ('Exports', 2015.0, '14/03/2015', 'Saturday', 'United States', 'All', 'All', '$', 23000000.0, 1282000000.0) .
success insertion of row ('Exports', 2016.0, '23/11/2016', 'Wednesday', 'China', 'Meat and edible offal', 'All', 'Tonnes', 0.0, 191000.0) .
success insertion of row ('Imports', 2019.0, '08/05/2019', 'Wednesday', 'China', 'All', 'All', '$', 42000000.0, 4147000000.0) .
success insertion of row ('Imports', 2019.0, '28/09/2019', 'Saturday', 'All', 'All', 'Sea', '$', 12000000.0, 36573000000.0) .
success insertion of row ('Exports', 2017.0, '22/11/2017', 'Wednesday', 'All', 'All', 'Sea', '$', 129000000.0, 41857000000.0) .
success insertion of row ('Exports', 2017.0, '30/08/2017', 'Wednesday', 'Japan', 'All', 'All', '$', 3000000.0, 2221000000.0) .
success insertion of row ('Imports', 2020.0, '15/12/2020', 'Tuesday', 'Australia', 'All', 'All', '$', 30000000.0, 6603000000.0) .
success insertion of row ('Imports', 2015.0, '02/09/2015', 'Wednesday', 'China', 'All', 'All', '$', 52000000.0, 6442000000.0) .
success insertion of row ('Exports', 2015.0, '31/07/2015', 'Friday', 'All', 'Fruit', 'All', '$', 12000000.0, 1677000000.0) .
success insertion of row ('Exports', 2021.0, '25/09/2021', 'Saturday', 'East Asia (excluding China)', 'All', 'All', '$', 41000000.0, 10488000000.0) .
success insertion of row ('Exports', 2021.0, '15/03/2021', 'Monday', 'East Asia (excluding China)', 'All', 'All', '$', 65000000.0, 2399000000.0) .
success insertion of row ('Exports', 2020.0, '13/08/2020', 'Thursday', 'All', 'Meat and edible offal', 'All', '$', 18000000.0, 5668000000.0) .
success insertion of row ('Imports', 2015.0, '29/11/2015', 'Sunday', 'China', 'All', 'All', '$', 9000000.0, 9367000000.0) .
success insertion of row ('Exports', 2021.0, '01/12/2021', 'Wednesday', 'European Union (27)', 'All', 'All', '$', 16000000.0, 3739000000.0) .
success insertion of row ('Exports', 2019.0, '19/04/2019', 'Friday', 'United States', 'Meat and edible offal', 'All', 'Tonnes', 1000.0, 73000.0) .
success insertion of row ('Imports', 2021.0, '16/09/2021', 'Thursday', 'All', 'All', 'Sea', '$', 240000000.0, 37508000000.0) .
success insertion of row ('Exports', 2015.0, '21/02/2015', 'Saturday', 'All', 'All', 'Sea', '$', 169000000.0, 5910000000.0) .
success insertion of row ('Imports', 2016.0, '26/11/2016', 'Saturday', 'All', 'Non-food manufactured goods', 'All', '$', 17000000.0, 36354000000.0) .
success insertion of row ('Exports', 2015.0, '02/12/2015', 'Wednesday', 'All', 'Fruit', 'All', '$', 0.0, 2272000000.0) .
success insertion of row ('Imports', 2021.0, '03/02/2021', 'Wednesday', 'United Kingdom', 'All', 'All', '$', 4000000.0, 136000000.0) .
success insertion of row ('Imports', 2019.0, '12/03/2019', 'Tuesday', 'China', 'All', 'All', '$', 29000000.0, 2374000000.0) .
success insertion of row ('Imports', 2019.0, '09/03/2019', 'Saturday', 'China', 'All', 'All', '$', 3000000.0, 2309000000.0) .
success insertion of row ('Imports', 2016.0, '02/03/2016', 'Wednesday', 'China', 'Mechanical machinery and equip', 'All', '$', 6000000.0, 264000000.0) .
success insertion of row ('Imports', 2017.0, '29/07/2017', 'Saturday', 'All', 'Non-food manufactured goods', 'All', '$', 23000000.0, 22991000000.0) .
success insertion of row ('Imports', 2015.0, '05/11/2015', 'Thursday', 'Australia', 'All', 'All', '$', 28000000.0, 5245000000.0) .
success insertion of row ('Exports', 2015.0, '12/01/2015', 'Monday', 'Total (excluding China)', 'All', 'All', '$', 137000000.0, 954000000.0) .
success insertion of row ('Reimports', 2015.0, '12/07/2015', 'Sunday', 'All', 'All', 'All', '$', 0.0, 107000000.0) .
success insertion of row ('Exports', 2018.0, '28/10/2018', 'Sunday', 'United States', 'All', 'All', '$', 9000000.0, 4547000000.0) .
success insertion of row ('Exports', 2017.0, '16/03/2017', 'Thursday', 'United Kingdom', 'All', 'All', '$', 7000000.0, 296000000.0) .
success insertion of row ('Exports', 2016.0, '18/06/2016', 'Saturday', 'China', 'All', 'All', '$', 33000000.0, 4411000000.0) .
success insertion of row ('Exports', 2016.0, '04/08/2016', 'Thursday', 'China', 'All', 'All', '$', 20000000.0, 5459000000.0) .
success insertion of row ('Imports', 2017.0, '18/11/2017', 'Saturday', 'All', 'Non-food manufactured goods', 'All', '$', 21000000.0, 37556000000.0) .
success insertion of row ('Imports', 2015.0, '23/06/2015', 'Tuesday', 'China', 'All', 'All', '$', 39000000.0, 4283000000.0) .
success insertion of row ('Imports', 2016.0, '22/02/2016', 'Monday', 'All', 'Mechanical machinery and equip', 'All', '$', 37000000.0, 886000000.0) .
success insertion of row ('Imports', 2016.0, '06/03/2016', 'Sunday', 'Australia', 'All', 'All', '$', 2000000.0, 1131000000.0) .
success insertion of row ('Imports', 2017.0, '07/12/2017', 'Thursday', 'All', 'Mechanical machinery and equip', 'All', '$', 38000000.0, 7576000000.0) .
success insertion of row ('Imports', 2021.0, '21/07/2021', 'Wednesday', 'All', 'All', 'Air', '$', 49000000.0, 7380000000.0) .
success insertion of row ('Exports', 2017.0, '22/01/2017', 'Sunday', 'Australia', 'All', 'All', '$', 19000000.0, 435000000.0) .
success insertion of row ('Exports', 2020.0, '01/03/2020', 'Sunday', 'United States', 'All', 'All', '$', 2000000.0, 1030000000.0) .
success insertion of row ('Exports', 2021.0, '13/12/2021', 'Monday', 'All', 'Fruit', 'All', '$', 1000000.0, 3891000000.0) .
success insertion of row ('Exports', 2020.0, '08/03/2020', 'Sunday', 'All', 'Meat and edible offal', 'All', 'Tonnes', 1000.0, 209000.0) .
success insertion of row ('Imports', 2021.0, '29/08/2021', 'Sunday', 'China', 'Mechanical machinery and equip', 'All', '$', 2000000.0, 1828000000.0) .
success insertion of row ('Exports', 2018.0, '04/10/2018', 'Thursday', 'Total (excluding China)', 'All', 'All', '$', 106000000.0, 33271000000.0) .
success insertion of row ('Imports', 2017.0, '28/11/2017', 'Tuesday', 'All', 'Non-food manufactured goods', 'All', '$', 156000000.0, 39260000000.0) .
success insertion of row ('Exports', 2015.0, '18/11/2015', 'Wednesday', 'China', 'Meat and edible offal', 'All', 'Tonnes', 0.0, 192000.0) .
success insertion of row ('Imports', 2016.0, '20/01/2016', 'Wednesday', 'All', 'Electrical machinery and equip', 'All', '$', 15000000.0, 191000000.0) .
success insertion of row ('Exports', 2021.0, '23/08/2021', 'Monday', 'Australia', 'All', 'All', '$', 6000000.0, 4943000000.0) .
success insertion of row ('Imports', 2015.0, '10/08/2015', 'Monday', 'All', 'Non-food manufactured goods', 'All', '$', 151000000.0, 22599000000.0) .
success insertion of row ('Exports', 2017.0, '14/10/2017', 'Saturday', 'All', 'Meat and edible offal', 'All', '$', 10000000.0, 5174000000.0) .
success insertion of row ('Exports', 2015.0, '23/12/2015', 'Wednesday', 'East Asia (excluding China)', 'All', 'All', '$', 9000000.0, 10982000000.0) .
success insertion of row ('Exports', 2015.0, '17/08/2015', 'Monday', 'All', 'Meat and edible offal', 'All', 'Tonnes', 3000.0, 687000.0) .
success insertion of row ('Exports', 2015.0, '08/02/2015', 'Sunday', 'Japan', 'All', 'All', '$', 2000000.0, 249000000.0) .
success insertion of row ('Imports', 2015.0, '09/12/2015', 'Wednesday', 'China', 'All', 'All', '$', 40000000.0, 9716000000.0) .
success insertion of row ('Exports', 2016.0, '12/10/2016', 'Wednesday', 'China', 'Meat and edible offal', 'All', '$', 0.0, 826000000.0) .
success insertion of row ('Imports', 2015.0, '25/07/2015', 'Saturday', 'All', 'All', 'Air', '$', 11000000.0, 6234000000.0) .
success insertion of row ('Imports', 2021.0, '26/10/2021', 'Tuesday', 'All', 'All', 'All', '$', 526000000.0, 55799000000.0) .
success insertion of row ('Imports', 2015.0, '21/10/2015', 'Wednesday', 'Australia', 'All', 'All', '$', 31000000.0, 4931000000.0) .